server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Franferrreras/SpringCloudD3S2.git
          search-paths:
          - config-data
  application:
    name: config-service